namespace IFRS.models;

/// <summary>
/// Describes the category of notification generated by the system.
/// </summary>
public enum NotificationType
{
    LeaseExpiryAlert = 1,
    PaymentDueReminder = 2,
    ContractRenewalReminder = 3,
    MissingDocumentAlert = 4,
    LeaseTerminatedAlert = 5,
    UserActivityAlert = 6
}
