// <auto-generated />
using System;
using System.Text.Json;
using IFRS.Data;
using IFRS.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IFRS.Migrations
{
    [DbContext(typeof(IFRSDbContext))]
    partial class IFRSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "user_role", new[] { "admin", "data_entry", "auditor" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IFRS.models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk_branch_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("branch_code");

                    b.Property<string>("BranchName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("branch_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Lessee")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lessee");

                    b.Property<string>("OracleCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oracle_code");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BranchId");

                    b.ToTable("branch");
                });

            modelBuilder.Entity("IFRS.models.EntityChangeRequest", b =>
                {
                    b.Property<int>("EntityChangeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk_entity_change_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityChangeRequestId"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<DateTime?>("EntityUpdatedAtSnapshot")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("entity_updated_at_snapshot");

                    b.Property<JsonElement>("NewValueSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value_snapshot");

                    b.Property<JsonElement?>("OldValueSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value_snapshot");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("RequestComments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("request_comments");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("requested_at");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("integer")
                        .HasColumnName("requested_by");

                    b.Property<string>("ReviewComments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_comments");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("EntityChangeRequestId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("Status", "EntityType", "EntityId");

                    b.ToTable("entity_change_request");
                });

            modelBuilder.Entity("IFRS.models.Lease", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk_lease_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaseId"));

                    b.Property<decimal?>("AgreementValue")
                        .HasColumnType("numeric")
                        .HasColumnName("agreement_value");

                    b.Property<decimal?>("AnnualRate")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_rate");

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Extensions")
                        .HasColumnType("text")
                        .HasColumnName("extensions");

                    b.Property<bool>("IsPaymentAtBeginning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid_at_beginning");

                    b.Property<string>("LeaseNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lease_no");

                    b.Property<string>("LeasePropertyAddress")
                        .HasColumnType("text")
                        .HasColumnName("lease_property_address");

                    b.Property<string>("LeaseStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lease_status");

                    b.Property<int?>("LessorId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_lessor_id");

                    b.Property<int?>("NoticePeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("notice_period_months");

                    b.Property<int?>("NumberOfYears")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_years");

                    b.Property<decimal?>("RefundableDeposit")
                        .HasColumnType("numeric")
                        .HasColumnName("refundable_deposit");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<decimal?>("RentAdvance")
                        .HasColumnType("numeric")
                        .HasColumnName("rent_advance");

                    b.Property<int?>("RentAdvancePeriod")
                        .HasColumnType("integer")
                        .HasColumnName("rent_advance_period");

                    b.Property<int?>("Sqft")
                        .HasColumnType("integer")
                        .HasColumnName("sqft");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("UtilityBill")
                        .HasColumnType("numeric")
                        .HasColumnName("utility_bill");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("numeric")
                        .HasColumnName("vat_rate");

                    b.Property<decimal?>("WhtRate")
                        .HasColumnType("numeric")
                        .HasColumnName("wht_rate");

                    b.HasKey("LeaseId");

                    b.HasIndex("BranchId");

                    b.HasIndex("LessorId");

                    b.ToTable("lease");
                });

            modelBuilder.Entity("IFRS.models.LeasePaymentSchedule", b =>
                {
                    b.Property<int>("PaymentScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk_payment_schedule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("GrossAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_amount");

                    b.Property<int?>("LeaseId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_lease_id");

                    b.Property<int?>("LeaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("lease_year");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PaymentScheduleId");

                    b.HasIndex("LeaseId");

                    b.ToTable("lease_payment_schedule");
                });

            modelBuilder.Entity("IFRS.models.Lessor", b =>
                {
                    b.Property<int>("LessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk_lessor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessorId"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_number");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BankCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_code");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Nic")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nic");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LessorId");

                    b.ToTable("lessor");
                });

            modelBuilder.Entity("IFRS.models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.HasIndex("UserId", "Type", "ReferenceType", "ReferenceId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("IFRS.models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk_refresh_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_user_id");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("IFRS.models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk_user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("IFRS.models.EntityChangeRequest", b =>
                {
                    b.HasOne("IFRS.models.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IFRS.models.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("IFRS.models.Lease", b =>
                {
                    b.HasOne("IFRS.models.Branch", "Branch")
                        .WithMany("Leases")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IFRS.models.Lessor", "Lessor")
                        .WithMany("Leases")
                        .HasForeignKey("LessorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Lessor");
                });

            modelBuilder.Entity("IFRS.models.LeasePaymentSchedule", b =>
                {
                    b.HasOne("IFRS.models.Lease", "Lease")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("IFRS.models.Notification", b =>
                {
                    b.HasOne("IFRS.models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IFRS.models.RefreshToken", b =>
                {
                    b.HasOne("IFRS.models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IFRS.models.Branch", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("IFRS.models.Lease", b =>
                {
                    b.Navigation("PaymentSchedules");
                });

            modelBuilder.Entity("IFRS.models.Lessor", b =>
                {
                    b.Navigation("Leases");
                });
#pragma warning restore 612, 618
        }
    }
}
